# Generated by Django 3.2.8 on 2021-11-15 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInitial',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='Cloud_Project/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileProcessed',
            fields=[
                ('id_file_cleared', models.AutoField(primary_key=True, serialize=False)),
                ('file_cleared', models.FileField(upload_to='Cloud_Project/')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudProjectApp.fileinitial')),
            ],
        ),
    ]
