# Generated by Django 3.2.8 on 2021-11-07 19:35

import CloudProjectApp.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='Documents/', validators=[CloudProjectApp.validators.validate_file_extension])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileProcessed',
            fields=[
                ('file', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CloudProjectApp.file')),
                ('file_cleared', models.FileField(upload_to='Documents/')),
            ],
        ),
    ]
