# Generated by Django 3.2.8 on 2021-11-13 12:49

import CloudProjectApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CloudProjectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprocessed',
            name='file_cleared',
            field=models.FileField(upload_to='Documents/', validators=[CloudProjectApp.validators.validate_file_extension]),
        ),
    ]
