# Generated by Django 3.2.8 on 2021-11-14 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CloudProjectApp', '0002_alter_fileprocessed_file_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='Cloud_Project/'),
        ),
        migrations.AlterField(
            model_name='fileprocessed',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CloudProjectApp.file'),
        ),
        migrations.AlterField(
            model_name='fileprocessed',
            name='file_cleared',
            field=models.FileField(upload_to='Cloud_Project/'),
        ),
    ]
