# Generated by Django 3.2.8 on 2021-11-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CloudProjectApp', '0003_auto_20211114_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileInitial',
        ),
    ]
